vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        recipe_images:
            uri_prefix: '%recipe_images%'
            upload_destination: '%kernel.project_dir%/public%recipe_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
