vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        recipe_images:
            uri_prefix: /public/build/images/recette
            upload_destination: "%kernel.project_dir%/public/build/images/recette"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

